<div class="position-fixed bg-white azul-escuro p-2 w-100 border-bottom">
    <div class="container-fluid d-flex justify-content-between align-items-center">
        <div class="navbar-brand">
            <span><i class="fas fa-check-double azul-claro"></i> Youtasks</span>
        </div>

        <div>
            Gerenciamento de tarefas
        </div>
    </div>
</div>

<div class="d-flex justify-content-center align-items-center flex-column h-100">
    <div class="border rounded" id="login_box"> <!-- Login Box -->
        <div class="azul-escuro text-center">
            <h3>Login</h3>
        </div>

        <div>
            <form action="/auth" method="POST">
                <input type="email" name="email" id="email" placeholder="Email" class="form-control bg-light">
                <input type="password" name="senha" id="senha" placeholder="Senha" class="form-control bg-light">

                <button type="submit" class="btn btn-color w-100">Entrar</button>
            </form>
        </div>

        <div class="text-center mt-3">
            <small><a href="#modalEmail" data-bs-toggle="modal" class="mt-3 azul-claro">Esqueci minha senha</a></small>
        </div>
    </div> <!-- Login Box -->

    <div class="p-3 bg-white rounded border" id="cadastroBox">
        <small>Não tem uma conta? <a href="#cadastrarUsuario" data-bs-toggle="modal" class="amarelo">Cadastre-se</a></small>
    </div>

    <div class="mt-2">
        <small class="text-secondary"><?= $this->view->ano ?> &copy; Youtasks</small>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="cadastrarUsuario" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-light">
            <div class="modal-header">
                <h5 class="modal-title">Cadastre-se</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form action="/cadastrar_usuario" method="POST">
                <div class="row">
                    <div class="col-md-12">
                        <label for="nome">Nome</label>
                        <input type="text" name="nome" id="nome" placeholder="4 caracteres ou mais" class="form-control">
                        <small id="msgNome" class="text-danger"></small>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email_cadastro" placeholder="email@gmail.com" class="form-control">
                        <small id="msgEmail" class="text-danger"></small>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label for="data">Data de nascimento</label>
                        <input type="date" name="data" id="data" class="form-control" required>
                    </div>

                    <div class="col-md-6">
                        <label for="senha">Senha</label>
                        <input type="password" name="senha" id="senha_cadastro" placeholder="6 caracteres ou mais" class="form-control">
                        <small id="msgSenha" class="text-danger"></small>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-color-dark" data-bs-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-color" id="cadastrar">Cadastrar</button>
                </form>
            </div>
    </div>
</div>
</div>

<?php if($this->view->msg != '') { ?>
    <div class="toast bg-color" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                <?= $this->view->msg ?>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
<?php } ?>




<!-- Modal -->
<div class="modal fade" id="modalEmail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-light">
            <div class="modal-header">
                <h5 class="modal-title">Digite seu email</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form action="/redefinir_senha" method="POST">
                    <div class="row">
                        <div class="col-md-12">
                            <input type="text" name="email" id="soli_email" placeholder="Email" class="form-control">
                        </div>
                    </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-color-dark" data-bs-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-color">Enviar</button>
                </form>
            </div>
    </div>
</div>
</div>

